// src/pages/UploadProof.tsx
import { useState } from "react";
import { useAuth } from "@clerk/clerk-react";
import {
  UploadCloud,
  CheckCircle2,
  ArrowLeft,
  ShieldCheck,
  Lock,
  AlertCircle,
} from "lucide-react";
import { useNavigate } from "react-router-dom";

export default function UploadProof() {
  const isClerkEnabled = !!import.meta.env.VITE_CLERK_PUBLISHABLE_KEY;
  const { getToken } = isClerkEnabled ? useAuth() : { getToken: async () => null };
  const navigate = useNavigate();

  const [txn, setTxn] = useState("");
  const [date, setDate] = useState("");
  const [url, setUrl] = useState("");
  const [loading, setLoading] = useState(false);

  const isValid = txn.length >= 6 && date && url.startsWith("http");

  const submit = async () => {
    if (!isValid || loading) return;

    setLoading(true);
    const token = await getToken();

    try {
      await fetch(
        `${import.meta.env.VITE_API_URL}/api/payments/submit-proof`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${token}`,
          },
          body: JSON.stringify({
            transactionId: txn,
            paymentDate: date,
            paymentProofUrl: url,
          }),
        }
      );

      navigate("/dashboard", {
        state: { submitted: true },
      });
    } catch (err) {
      alert("Submission failed. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-[#0b0d12] text-white px-4 sm:px-6 lg:px-12 py-16">
      <div className="max-w-6xl mx-auto">

        <button
          onClick={() => navigate(-1)}
          className="mb-8 inline-flex items-center gap-2 text-sm text-white/60 hover:text-white transition"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to payment methods
        </button>

        <div className="bg-black/60 border border-white/10 rounded-3xl p-6 sm:p-8 lg:p-12 backdrop-blur">
          <div className="mb-10">
            <div className="flex items-center justify-between text-xs text-white/40 mb-2">
              <span>Registration</span>
              <span>Payment</span>
              <span className="text-accent">Confirmation</span>
            </div>
            <div className="h-1 w-full bg-white/10 rounded-full overflow-hidden">
              <div className="h-full w-full bg-accent rounded-full" />
            </div>
          </div>

          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-12">
            <div>
              <h1 className="text-2xl sm:text-3xl font-semibold">
                Payment confirmation
              </h1>
              <p className="text-sm text-white/60 mt-1">
                Provide transaction details to complete registration
              </p>
            </div>

            <span className="text-xs bg-accent/20 text-accent px-3 py-1 rounded-full">
              Step 3 of 3
            </span>
          </div>


          <div className="grid grid-cols-1 lg:grid-cols-3 gap-12">
            {/* LEFT — FORM */}
            <div className="lg:col-span-2 space-y-8">
              {/* Transaction ID */}
              <div>
                <label className="text-sm font-medium">
                  Transaction ID / UTR
                </label>
                <input
                  value={txn}
                  onChange={(e) => setTxn(e.target.value)}
                  placeholder="e.g. 123456789012"
                  className="mt-2 w-full bg-black/40 border border-white/15 rounded-xl px-4 py-3 focus:outline-none focus:border-accent"
                />
                <p className="text-xs text-white/50 mt-1">
                  This is generated by your bank or UPI app
                </p>
              </div>

              {/* Date */}
              <div>
                <label className="text-sm font-medium">
                  Payment date
                </label>
                <input
                  type="date"
                  value={date}
                  onChange={(e) => setDate(e.target.value)}
                  className="mt-2 w-full bg-black/40 border border-white/15 rounded-xl px-4 py-3 focus:outline-none focus:border-accent"
                />
              </div>

              {/* URL */}
              <div>
                <label className="text-sm font-medium">
                  Payment receipt URL
                </label>
                <input
                  value={url}
                  onChange={(e) => setUrl(e.target.value)}
                  placeholder="https://drive.google.com/..."
                  className="mt-2 w-full bg-black/40 border border-white/15 rounded-xl px-4 py-3 focus:outline-none focus:border-accent"
                />
                <p className="text-xs text-white/50 mt-1">
                  Upload your receipt to Drive / Cloudinary and
                  paste the public link
                </p>
              </div>

              {/* Validation */}
              {!isValid && (
                <div className="flex items-start gap-2 text-xs text-yellow-400/80 bg-yellow-400/10 border border-yellow-400/20 rounded-xl p-3">
                  <AlertCircle className="w-4 h-4 mt-0.5" />
                  Please fill all fields correctly before submitting
                </div>
              )}
            </div>

            {/* RIGHT — SUMMARY & TRUST */}
            <div className="flex flex-col justify-between space-y-10">
              {/* What happens next */}
              <div className="bg-white/5 border border-white/10 rounded-2xl p-6 space-y-4 text-sm">
                <p className="font-medium flex items-center gap-2">
                  <ShieldCheck className="w-4 h-4 text-accent" />
                  What happens next?
                </p>

                <ul className="space-y-2 text-white/70 list-disc list-inside">
                  <li>Payment proof is reviewed manually</li>
                  <li>Verification takes 24–48 hours</li>
                  <li>Status updates appear on dashboard</li>
                  <li>Email confirmation after approval</li>
                </ul>
              </div>

              {/* Submit */}
              <div className="space-y-4">
                <button
                  onClick={submit}
                  disabled={!isValid || loading}
                  className={`w-full flex items-center justify-center gap-2 py-4 rounded-xl font-medium text-lg transition ${
                    isValid
                      ? "bg-accent text-black hover:opacity-90"
                      : "bg-white/10 text-white/40 cursor-not-allowed"
                  }`}
                >
                  {loading ? (
                    "Submitting securely..."
                  ) : (
                    <>
                      <UploadCloud className="w-5 h-5" />
                      Submit for verification
                    </>
                  )}
                </button>

                {/* Trust badges */}
                <div className="flex flex-col gap-2 text-xs text-white/50">
                  <div className="flex items-center gap-2">
                    <Lock className="w-4 h-4 text-accent" />
                    SSL encrypted submission
                  </div>
                  <div className="flex items-center gap-2">
                    <CheckCircle2 className="w-4 h-4 text-accent" />
                    Reviewed by NCTAIDS finance team
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
